#
# Generated by the NeXT Interface Builder.
#
# NOTE: Do NOT change this file -- Interface Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = WorldWideWeb

INTERFACES = WorldWideWeb.nib
CLASSES = Anchor.m HTStyle.m HyperAccess.m HyperManager.m HyperText.m \
          StyleToy.m TextToy.m WWWPageLayout.m
MFILES = WorldWideWeb_main.m
CFILES = HTAccess.c HTFTP.c HTFile.c HTParse.c HTTCP.c HTTP.c
HFILES = HTAccess.h HTFTP.h HTFile.h HTParse.h HTTCP.h HTTP.h HTUtils.h \
         WWW.h tcp.h
TIFFFILES = icon1.tiff
APPICON = icon2.tiff
DOCICONS = icon1.tiff

SOURCEMODE = 444

LIBS = -lNeXT_s -lsys_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = -lNeXT_p -lsys_p

MAKEFILEDIR = /usr/lib/nib
ICONSECTIONS =	-sectcreate __ICON app icon2.tiff \
		-sectcreate __ICON html icon1.tiff

INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755

-include Makefile.preamble

include $(MAKEFILEDIR)/app.make

-include Makefile.postamble

-include Makefile.dependencies
