
/* Generated by Interface Builder */

#import <objc/Object.h>

@interface StyleToy:Object
{
    id	TabForm;
    id	ParameterForm;
    id	StylePanel;
    id	NameForm;
}

+new;

- loadDefaultStyleSheet;
- setTabForm:anObject;
- setParameterForm:anObject;
- setStylePanel:anObject;
- setNameForm:anObject;
- NextButton:sender;
- FindUnstyledButton:sender;
- ApplyButton:sender;
- PreviousButton:sender;
- SetButton:sender;
- PickButton:sender;
- ApplyToSimilar:sender;
- open:sender;
- saveAs:sender;
@end
